# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Popcorn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Popcorn
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'RxDataSources', '~> 4.0'
  pod 'Moya/RxSwift', '~> 14.0'
  
  pod 'Kingfisher'
  pod 'Hero'
  pod 'FloatingPanel'
  pod 'SkeletonView'
  
  target 'PopcornTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PopcornUITests' do
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end
