# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Popcorn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Popcorn
  pod 'Alamofire', '~> 5.2'
  pod 'IGListKit', '~> 4.0.0'
  pod 'Nuke', '~> 9.0'
  pod 'Hero'
  pod 'FloatingPanel'
  pod 'SkeletonView'
  
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'RxDataSources', '~> 4.0'
  pod 'Moya/RxSwift', '~> 14.0'

  target 'PopcornTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PopcornUITests' do
    # Pods for testing
  end

end
